<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.yunfan.mall</groupId>
    <artifactId>yunfan</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>yunfan</name>
    <description>聚合服务</description>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <modules>
        <module>yunfan-common</module>

        <module>yunfan-ai-server</module>

        <module>yunfan-coupon</module>
        <module>yunfan-gateway</module>
        <module>yunfan-member</module>
        <module>yunfan-order</module>
        <module>yunfan-search</module>

        <module>yunfan-product</module>

        <module>yunfan-ware</module>
        <module>yunfan-seckill</module>
        <module>renren-generator</module>
        <module>yunfan-third-party</module>

        <module>yunfan-auth-server</module>
        <module>yunfan-cart</module>
        <module>yunfan-test-sso-client</module>
        <module>yunfan-test-sso-server</module>
        <module>renren-fast</module>

    </modules>


</project>
